package com.dragon.alphadiet.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dragon.alphadiet.entity.Diet;
import com.dragon.alphadiet.entity.Recipe;

import com.dragon.alphadiet.greendao.DietDao;
import com.dragon.alphadiet.greendao.RecipeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dietDaoConfig;
    private final DaoConfig recipeDaoConfig;

    private final DietDao dietDao;
    private final RecipeDao recipeDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dietDaoConfig = daoConfigMap.get(DietDao.class).clone();
        dietDaoConfig.initIdentityScope(type);

        recipeDaoConfig = daoConfigMap.get(RecipeDao.class).clone();
        recipeDaoConfig.initIdentityScope(type);

        dietDao = new DietDao(dietDaoConfig, this);
        recipeDao = new RecipeDao(recipeDaoConfig, this);

        registerDao(Diet.class, dietDao);
        registerDao(Recipe.class, recipeDao);
    }
    
    public void clear() {
        dietDaoConfig.clearIdentityScope();
        recipeDaoConfig.clearIdentityScope();
    }

    public DietDao getDietDao() {
        return dietDao;
    }

    public RecipeDao getRecipeDao() {
        return recipeDao;
    }

}
